# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_pyphy')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_pyphy')
    _pyphy = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyphy', [dirname(__file__)])
        except ImportError:
            import _pyphy
            return _pyphy
        try:
            _mod = imp.load_module('_pyphy', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _pyphy = swig_import_helper()
    del swig_import_helper
else:
    import _pyphy
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyphy.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _pyphy.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyphy.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyphy.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyphy.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyphy.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyphy.SwigPyIterator_copy(self)

    def next(self):
        return _pyphy.SwigPyIterator_next(self)

    def __next__(self):
        return _pyphy.SwigPyIterator___next__(self)

    def previous(self):
        return _pyphy.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyphy.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyphy.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyphy.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyphy.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyphy.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyphy.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyphy.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _pyphy.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class CharVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CharVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CharVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyphy.CharVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyphy.CharVector___nonzero__(self)

    def __bool__(self):
        return _pyphy.CharVector___bool__(self)

    def __len__(self):
        return _pyphy.CharVector___len__(self)

    def __getslice__(self, i, j):
        return _pyphy.CharVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyphy.CharVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyphy.CharVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyphy.CharVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyphy.CharVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyphy.CharVector___setitem__(self, *args)

    def pop(self):
        return _pyphy.CharVector_pop(self)

    def append(self, x):
        return _pyphy.CharVector_append(self, x)

    def empty(self):
        return _pyphy.CharVector_empty(self)

    def size(self):
        return _pyphy.CharVector_size(self)

    def swap(self, v):
        return _pyphy.CharVector_swap(self, v)

    def begin(self):
        return _pyphy.CharVector_begin(self)

    def end(self):
        return _pyphy.CharVector_end(self)

    def rbegin(self):
        return _pyphy.CharVector_rbegin(self)

    def rend(self):
        return _pyphy.CharVector_rend(self)

    def clear(self):
        return _pyphy.CharVector_clear(self)

    def get_allocator(self):
        return _pyphy.CharVector_get_allocator(self)

    def pop_back(self):
        return _pyphy.CharVector_pop_back(self)

    def erase(self, *args):
        return _pyphy.CharVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyphy.new_CharVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyphy.CharVector_push_back(self, x)

    def front(self):
        return _pyphy.CharVector_front(self)

    def back(self):
        return _pyphy.CharVector_back(self)

    def assign(self, n, x):
        return _pyphy.CharVector_assign(self, n, x)

    def resize(self, *args):
        return _pyphy.CharVector_resize(self, *args)

    def insert(self, *args):
        return _pyphy.CharVector_insert(self, *args)

    def reserve(self, n):
        return _pyphy.CharVector_reserve(self, n)

    def capacity(self):
        return _pyphy.CharVector_capacity(self)
    __swig_destroy__ = _pyphy.delete_CharVector
    __del__ = lambda self: None
CharVector_swigregister = _pyphy.CharVector_swigregister
CharVector_swigregister(CharVector)

class UnsignedCharVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UnsignedCharVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UnsignedCharVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyphy.UnsignedCharVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyphy.UnsignedCharVector___nonzero__(self)

    def __bool__(self):
        return _pyphy.UnsignedCharVector___bool__(self)

    def __len__(self):
        return _pyphy.UnsignedCharVector___len__(self)

    def __getslice__(self, i, j):
        return _pyphy.UnsignedCharVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyphy.UnsignedCharVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyphy.UnsignedCharVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyphy.UnsignedCharVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyphy.UnsignedCharVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyphy.UnsignedCharVector___setitem__(self, *args)

    def pop(self):
        return _pyphy.UnsignedCharVector_pop(self)

    def append(self, x):
        return _pyphy.UnsignedCharVector_append(self, x)

    def empty(self):
        return _pyphy.UnsignedCharVector_empty(self)

    def size(self):
        return _pyphy.UnsignedCharVector_size(self)

    def swap(self, v):
        return _pyphy.UnsignedCharVector_swap(self, v)

    def begin(self):
        return _pyphy.UnsignedCharVector_begin(self)

    def end(self):
        return _pyphy.UnsignedCharVector_end(self)

    def rbegin(self):
        return _pyphy.UnsignedCharVector_rbegin(self)

    def rend(self):
        return _pyphy.UnsignedCharVector_rend(self)

    def clear(self):
        return _pyphy.UnsignedCharVector_clear(self)

    def get_allocator(self):
        return _pyphy.UnsignedCharVector_get_allocator(self)

    def pop_back(self):
        return _pyphy.UnsignedCharVector_pop_back(self)

    def erase(self, *args):
        return _pyphy.UnsignedCharVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyphy.new_UnsignedCharVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyphy.UnsignedCharVector_push_back(self, x)

    def front(self):
        return _pyphy.UnsignedCharVector_front(self)

    def back(self):
        return _pyphy.UnsignedCharVector_back(self)

    def assign(self, n, x):
        return _pyphy.UnsignedCharVector_assign(self, n, x)

    def resize(self, *args):
        return _pyphy.UnsignedCharVector_resize(self, *args)

    def insert(self, *args):
        return _pyphy.UnsignedCharVector_insert(self, *args)

    def reserve(self, n):
        return _pyphy.UnsignedCharVector_reserve(self, n)

    def capacity(self):
        return _pyphy.UnsignedCharVector_capacity(self)
    __swig_destroy__ = _pyphy.delete_UnsignedCharVector
    __del__ = lambda self: None
UnsignedCharVector_swigregister = _pyphy.UnsignedCharVector_swigregister
UnsignedCharVector_swigregister(UnsignedCharVector)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyphy.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyphy.IntVector___nonzero__(self)

    def __bool__(self):
        return _pyphy.IntVector___bool__(self)

    def __len__(self):
        return _pyphy.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _pyphy.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyphy.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyphy.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyphy.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyphy.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyphy.IntVector___setitem__(self, *args)

    def pop(self):
        return _pyphy.IntVector_pop(self)

    def append(self, x):
        return _pyphy.IntVector_append(self, x)

    def empty(self):
        return _pyphy.IntVector_empty(self)

    def size(self):
        return _pyphy.IntVector_size(self)

    def swap(self, v):
        return _pyphy.IntVector_swap(self, v)

    def begin(self):
        return _pyphy.IntVector_begin(self)

    def end(self):
        return _pyphy.IntVector_end(self)

    def rbegin(self):
        return _pyphy.IntVector_rbegin(self)

    def rend(self):
        return _pyphy.IntVector_rend(self)

    def clear(self):
        return _pyphy.IntVector_clear(self)

    def get_allocator(self):
        return _pyphy.IntVector_get_allocator(self)

    def pop_back(self):
        return _pyphy.IntVector_pop_back(self)

    def erase(self, *args):
        return _pyphy.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyphy.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyphy.IntVector_push_back(self, x)

    def front(self):
        return _pyphy.IntVector_front(self)

    def back(self):
        return _pyphy.IntVector_back(self)

    def assign(self, n, x):
        return _pyphy.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _pyphy.IntVector_resize(self, *args)

    def insert(self, *args):
        return _pyphy.IntVector_insert(self, *args)

    def reserve(self, n):
        return _pyphy.IntVector_reserve(self, n)

    def capacity(self):
        return _pyphy.IntVector_capacity(self)
    __swig_destroy__ = _pyphy.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _pyphy.IntVector_swigregister
IntVector_swigregister(IntVector)

class UnsignedIntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UnsignedIntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UnsignedIntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyphy.UnsignedIntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyphy.UnsignedIntVector___nonzero__(self)

    def __bool__(self):
        return _pyphy.UnsignedIntVector___bool__(self)

    def __len__(self):
        return _pyphy.UnsignedIntVector___len__(self)

    def __getslice__(self, i, j):
        return _pyphy.UnsignedIntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyphy.UnsignedIntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyphy.UnsignedIntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyphy.UnsignedIntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyphy.UnsignedIntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyphy.UnsignedIntVector___setitem__(self, *args)

    def pop(self):
        return _pyphy.UnsignedIntVector_pop(self)

    def append(self, x):
        return _pyphy.UnsignedIntVector_append(self, x)

    def empty(self):
        return _pyphy.UnsignedIntVector_empty(self)

    def size(self):
        return _pyphy.UnsignedIntVector_size(self)

    def swap(self, v):
        return _pyphy.UnsignedIntVector_swap(self, v)

    def begin(self):
        return _pyphy.UnsignedIntVector_begin(self)

    def end(self):
        return _pyphy.UnsignedIntVector_end(self)

    def rbegin(self):
        return _pyphy.UnsignedIntVector_rbegin(self)

    def rend(self):
        return _pyphy.UnsignedIntVector_rend(self)

    def clear(self):
        return _pyphy.UnsignedIntVector_clear(self)

    def get_allocator(self):
        return _pyphy.UnsignedIntVector_get_allocator(self)

    def pop_back(self):
        return _pyphy.UnsignedIntVector_pop_back(self)

    def erase(self, *args):
        return _pyphy.UnsignedIntVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyphy.new_UnsignedIntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyphy.UnsignedIntVector_push_back(self, x)

    def front(self):
        return _pyphy.UnsignedIntVector_front(self)

    def back(self):
        return _pyphy.UnsignedIntVector_back(self)

    def assign(self, n, x):
        return _pyphy.UnsignedIntVector_assign(self, n, x)

    def resize(self, *args):
        return _pyphy.UnsignedIntVector_resize(self, *args)

    def insert(self, *args):
        return _pyphy.UnsignedIntVector_insert(self, *args)

    def reserve(self, n):
        return _pyphy.UnsignedIntVector_reserve(self, n)

    def capacity(self):
        return _pyphy.UnsignedIntVector_capacity(self)
    __swig_destroy__ = _pyphy.delete_UnsignedIntVector
    __del__ = lambda self: None
UnsignedIntVector_swigregister = _pyphy.UnsignedIntVector_swigregister
UnsignedIntVector_swigregister(UnsignedIntVector)

class FloatVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyphy.FloatVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyphy.FloatVector___nonzero__(self)

    def __bool__(self):
        return _pyphy.FloatVector___bool__(self)

    def __len__(self):
        return _pyphy.FloatVector___len__(self)

    def __getslice__(self, i, j):
        return _pyphy.FloatVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyphy.FloatVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyphy.FloatVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyphy.FloatVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyphy.FloatVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyphy.FloatVector___setitem__(self, *args)

    def pop(self):
        return _pyphy.FloatVector_pop(self)

    def append(self, x):
        return _pyphy.FloatVector_append(self, x)

    def empty(self):
        return _pyphy.FloatVector_empty(self)

    def size(self):
        return _pyphy.FloatVector_size(self)

    def swap(self, v):
        return _pyphy.FloatVector_swap(self, v)

    def begin(self):
        return _pyphy.FloatVector_begin(self)

    def end(self):
        return _pyphy.FloatVector_end(self)

    def rbegin(self):
        return _pyphy.FloatVector_rbegin(self)

    def rend(self):
        return _pyphy.FloatVector_rend(self)

    def clear(self):
        return _pyphy.FloatVector_clear(self)

    def get_allocator(self):
        return _pyphy.FloatVector_get_allocator(self)

    def pop_back(self):
        return _pyphy.FloatVector_pop_back(self)

    def erase(self, *args):
        return _pyphy.FloatVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyphy.new_FloatVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyphy.FloatVector_push_back(self, x)

    def front(self):
        return _pyphy.FloatVector_front(self)

    def back(self):
        return _pyphy.FloatVector_back(self)

    def assign(self, n, x):
        return _pyphy.FloatVector_assign(self, n, x)

    def resize(self, *args):
        return _pyphy.FloatVector_resize(self, *args)

    def insert(self, *args):
        return _pyphy.FloatVector_insert(self, *args)

    def reserve(self, n):
        return _pyphy.FloatVector_reserve(self, n)

    def capacity(self):
        return _pyphy.FloatVector_capacity(self)
    __swig_destroy__ = _pyphy.delete_FloatVector
    __del__ = lambda self: None
FloatVector_swigregister = _pyphy.FloatVector_swigregister
FloatVector_swigregister(FloatVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyphy.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyphy.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _pyphy.DoubleVector___bool__(self)

    def __len__(self):
        return _pyphy.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _pyphy.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyphy.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyphy.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyphy.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyphy.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyphy.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _pyphy.DoubleVector_pop(self)

    def append(self, x):
        return _pyphy.DoubleVector_append(self, x)

    def empty(self):
        return _pyphy.DoubleVector_empty(self)

    def size(self):
        return _pyphy.DoubleVector_size(self)

    def swap(self, v):
        return _pyphy.DoubleVector_swap(self, v)

    def begin(self):
        return _pyphy.DoubleVector_begin(self)

    def end(self):
        return _pyphy.DoubleVector_end(self)

    def rbegin(self):
        return _pyphy.DoubleVector_rbegin(self)

    def rend(self):
        return _pyphy.DoubleVector_rend(self)

    def clear(self):
        return _pyphy.DoubleVector_clear(self)

    def get_allocator(self):
        return _pyphy.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _pyphy.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _pyphy.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyphy.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyphy.DoubleVector_push_back(self, x)

    def front(self):
        return _pyphy.DoubleVector_front(self)

    def back(self):
        return _pyphy.DoubleVector_back(self)

    def assign(self, n, x):
        return _pyphy.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _pyphy.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _pyphy.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _pyphy.DoubleVector_reserve(self, n)

    def capacity(self):
        return _pyphy.DoubleVector_capacity(self)
    __swig_destroy__ = _pyphy.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _pyphy.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class IntMatrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntMatrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntMatrix, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyphy.IntMatrix_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyphy.IntMatrix___nonzero__(self)

    def __bool__(self):
        return _pyphy.IntMatrix___bool__(self)

    def __len__(self):
        return _pyphy.IntMatrix___len__(self)

    def __getslice__(self, i, j):
        return _pyphy.IntMatrix___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyphy.IntMatrix___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyphy.IntMatrix___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyphy.IntMatrix___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyphy.IntMatrix___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyphy.IntMatrix___setitem__(self, *args)

    def pop(self):
        return _pyphy.IntMatrix_pop(self)

    def append(self, x):
        return _pyphy.IntMatrix_append(self, x)

    def empty(self):
        return _pyphy.IntMatrix_empty(self)

    def size(self):
        return _pyphy.IntMatrix_size(self)

    def swap(self, v):
        return _pyphy.IntMatrix_swap(self, v)

    def begin(self):
        return _pyphy.IntMatrix_begin(self)

    def end(self):
        return _pyphy.IntMatrix_end(self)

    def rbegin(self):
        return _pyphy.IntMatrix_rbegin(self)

    def rend(self):
        return _pyphy.IntMatrix_rend(self)

    def clear(self):
        return _pyphy.IntMatrix_clear(self)

    def get_allocator(self):
        return _pyphy.IntMatrix_get_allocator(self)

    def pop_back(self):
        return _pyphy.IntMatrix_pop_back(self)

    def erase(self, *args):
        return _pyphy.IntMatrix_erase(self, *args)

    def __init__(self, *args):
        this = _pyphy.new_IntMatrix(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyphy.IntMatrix_push_back(self, x)

    def front(self):
        return _pyphy.IntMatrix_front(self)

    def back(self):
        return _pyphy.IntMatrix_back(self)

    def assign(self, n, x):
        return _pyphy.IntMatrix_assign(self, n, x)

    def resize(self, *args):
        return _pyphy.IntMatrix_resize(self, *args)

    def insert(self, *args):
        return _pyphy.IntMatrix_insert(self, *args)

    def reserve(self, n):
        return _pyphy.IntMatrix_reserve(self, n)

    def capacity(self):
        return _pyphy.IntMatrix_capacity(self)
    __swig_destroy__ = _pyphy.delete_IntMatrix
    __del__ = lambda self: None
IntMatrix_swigregister = _pyphy.IntMatrix_swigregister
IntMatrix_swigregister(IntMatrix)

class UnsignedIntMatrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UnsignedIntMatrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UnsignedIntMatrix, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyphy.UnsignedIntMatrix_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyphy.UnsignedIntMatrix___nonzero__(self)

    def __bool__(self):
        return _pyphy.UnsignedIntMatrix___bool__(self)

    def __len__(self):
        return _pyphy.UnsignedIntMatrix___len__(self)

    def __getslice__(self, i, j):
        return _pyphy.UnsignedIntMatrix___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyphy.UnsignedIntMatrix___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyphy.UnsignedIntMatrix___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyphy.UnsignedIntMatrix___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyphy.UnsignedIntMatrix___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyphy.UnsignedIntMatrix___setitem__(self, *args)

    def pop(self):
        return _pyphy.UnsignedIntMatrix_pop(self)

    def append(self, x):
        return _pyphy.UnsignedIntMatrix_append(self, x)

    def empty(self):
        return _pyphy.UnsignedIntMatrix_empty(self)

    def size(self):
        return _pyphy.UnsignedIntMatrix_size(self)

    def swap(self, v):
        return _pyphy.UnsignedIntMatrix_swap(self, v)

    def begin(self):
        return _pyphy.UnsignedIntMatrix_begin(self)

    def end(self):
        return _pyphy.UnsignedIntMatrix_end(self)

    def rbegin(self):
        return _pyphy.UnsignedIntMatrix_rbegin(self)

    def rend(self):
        return _pyphy.UnsignedIntMatrix_rend(self)

    def clear(self):
        return _pyphy.UnsignedIntMatrix_clear(self)

    def get_allocator(self):
        return _pyphy.UnsignedIntMatrix_get_allocator(self)

    def pop_back(self):
        return _pyphy.UnsignedIntMatrix_pop_back(self)

    def erase(self, *args):
        return _pyphy.UnsignedIntMatrix_erase(self, *args)

    def __init__(self, *args):
        this = _pyphy.new_UnsignedIntMatrix(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyphy.UnsignedIntMatrix_push_back(self, x)

    def front(self):
        return _pyphy.UnsignedIntMatrix_front(self)

    def back(self):
        return _pyphy.UnsignedIntMatrix_back(self)

    def assign(self, n, x):
        return _pyphy.UnsignedIntMatrix_assign(self, n, x)

    def resize(self, *args):
        return _pyphy.UnsignedIntMatrix_resize(self, *args)

    def insert(self, *args):
        return _pyphy.UnsignedIntMatrix_insert(self, *args)

    def reserve(self, n):
        return _pyphy.UnsignedIntMatrix_reserve(self, n)

    def capacity(self):
        return _pyphy.UnsignedIntMatrix_capacity(self)
    __swig_destroy__ = _pyphy.delete_UnsignedIntMatrix
    __del__ = lambda self: None
UnsignedIntMatrix_swigregister = _pyphy.UnsignedIntMatrix_swigregister
UnsignedIntMatrix_swigregister(UnsignedIntMatrix)

class FloatMatrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatMatrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatMatrix, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyphy.FloatMatrix_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyphy.FloatMatrix___nonzero__(self)

    def __bool__(self):
        return _pyphy.FloatMatrix___bool__(self)

    def __len__(self):
        return _pyphy.FloatMatrix___len__(self)

    def __getslice__(self, i, j):
        return _pyphy.FloatMatrix___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyphy.FloatMatrix___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyphy.FloatMatrix___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyphy.FloatMatrix___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyphy.FloatMatrix___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyphy.FloatMatrix___setitem__(self, *args)

    def pop(self):
        return _pyphy.FloatMatrix_pop(self)

    def append(self, x):
        return _pyphy.FloatMatrix_append(self, x)

    def empty(self):
        return _pyphy.FloatMatrix_empty(self)

    def size(self):
        return _pyphy.FloatMatrix_size(self)

    def swap(self, v):
        return _pyphy.FloatMatrix_swap(self, v)

    def begin(self):
        return _pyphy.FloatMatrix_begin(self)

    def end(self):
        return _pyphy.FloatMatrix_end(self)

    def rbegin(self):
        return _pyphy.FloatMatrix_rbegin(self)

    def rend(self):
        return _pyphy.FloatMatrix_rend(self)

    def clear(self):
        return _pyphy.FloatMatrix_clear(self)

    def get_allocator(self):
        return _pyphy.FloatMatrix_get_allocator(self)

    def pop_back(self):
        return _pyphy.FloatMatrix_pop_back(self)

    def erase(self, *args):
        return _pyphy.FloatMatrix_erase(self, *args)

    def __init__(self, *args):
        this = _pyphy.new_FloatMatrix(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyphy.FloatMatrix_push_back(self, x)

    def front(self):
        return _pyphy.FloatMatrix_front(self)

    def back(self):
        return _pyphy.FloatMatrix_back(self)

    def assign(self, n, x):
        return _pyphy.FloatMatrix_assign(self, n, x)

    def resize(self, *args):
        return _pyphy.FloatMatrix_resize(self, *args)

    def insert(self, *args):
        return _pyphy.FloatMatrix_insert(self, *args)

    def reserve(self, n):
        return _pyphy.FloatMatrix_reserve(self, n)

    def capacity(self):
        return _pyphy.FloatMatrix_capacity(self)
    __swig_destroy__ = _pyphy.delete_FloatMatrix
    __del__ = lambda self: None
FloatMatrix_swigregister = _pyphy.FloatMatrix_swigregister
FloatMatrix_swigregister(FloatMatrix)

class DoubleMatrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleMatrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleMatrix, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyphy.DoubleMatrix_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyphy.DoubleMatrix___nonzero__(self)

    def __bool__(self):
        return _pyphy.DoubleMatrix___bool__(self)

    def __len__(self):
        return _pyphy.DoubleMatrix___len__(self)

    def __getslice__(self, i, j):
        return _pyphy.DoubleMatrix___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyphy.DoubleMatrix___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyphy.DoubleMatrix___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyphy.DoubleMatrix___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyphy.DoubleMatrix___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyphy.DoubleMatrix___setitem__(self, *args)

    def pop(self):
        return _pyphy.DoubleMatrix_pop(self)

    def append(self, x):
        return _pyphy.DoubleMatrix_append(self, x)

    def empty(self):
        return _pyphy.DoubleMatrix_empty(self)

    def size(self):
        return _pyphy.DoubleMatrix_size(self)

    def swap(self, v):
        return _pyphy.DoubleMatrix_swap(self, v)

    def begin(self):
        return _pyphy.DoubleMatrix_begin(self)

    def end(self):
        return _pyphy.DoubleMatrix_end(self)

    def rbegin(self):
        return _pyphy.DoubleMatrix_rbegin(self)

    def rend(self):
        return _pyphy.DoubleMatrix_rend(self)

    def clear(self):
        return _pyphy.DoubleMatrix_clear(self)

    def get_allocator(self):
        return _pyphy.DoubleMatrix_get_allocator(self)

    def pop_back(self):
        return _pyphy.DoubleMatrix_pop_back(self)

    def erase(self, *args):
        return _pyphy.DoubleMatrix_erase(self, *args)

    def __init__(self, *args):
        this = _pyphy.new_DoubleMatrix(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyphy.DoubleMatrix_push_back(self, x)

    def front(self):
        return _pyphy.DoubleMatrix_front(self)

    def back(self):
        return _pyphy.DoubleMatrix_back(self)

    def assign(self, n, x):
        return _pyphy.DoubleMatrix_assign(self, n, x)

    def resize(self, *args):
        return _pyphy.DoubleMatrix_resize(self, *args)

    def insert(self, *args):
        return _pyphy.DoubleMatrix_insert(self, *args)

    def reserve(self, n):
        return _pyphy.DoubleMatrix_reserve(self, n)

    def capacity(self):
        return _pyphy.DoubleMatrix_capacity(self)
    __swig_destroy__ = _pyphy.delete_DoubleMatrix
    __del__ = lambda self: None
DoubleMatrix_swigregister = _pyphy.DoubleMatrix_swigregister
DoubleMatrix_swigregister(DoubleMatrix)

class sDatExtremes(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, sDatExtremes, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, sDatExtremes, name)
    __repr__ = _swig_repr
    __swig_setmethods__["max"] = _pyphy.sDatExtremes_max_set
    __swig_getmethods__["max"] = _pyphy.sDatExtremes_max_get
    if _newclass:
        max = _swig_property(_pyphy.sDatExtremes_max_get, _pyphy.sDatExtremes_max_set)
    __swig_setmethods__["min"] = _pyphy.sDatExtremes_min_set
    __swig_getmethods__["min"] = _pyphy.sDatExtremes_min_get
    if _newclass:
        min = _swig_property(_pyphy.sDatExtremes_min_get, _pyphy.sDatExtremes_min_set)
    __swig_setmethods__["max_column"] = _pyphy.sDatExtremes_max_column_set
    __swig_getmethods__["max_column"] = _pyphy.sDatExtremes_max_column_get
    if _newclass:
        max_column = _swig_property(_pyphy.sDatExtremes_max_column_get, _pyphy.sDatExtremes_max_column_set)
    __swig_setmethods__["min_column"] = _pyphy.sDatExtremes_min_column_set
    __swig_getmethods__["min_column"] = _pyphy.sDatExtremes_min_column_get
    if _newclass:
        min_column = _swig_property(_pyphy.sDatExtremes_min_column_get, _pyphy.sDatExtremes_min_column_set)

    def __init__(self):
        this = _pyphy.new_sDatExtremes()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_sDatExtremes
    __del__ = lambda self: None
sDatExtremes_swigregister = _pyphy.sDatExtremes_swigregister
sDatExtremes_swigregister(sDatExtremes)

class DatLoad(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DatLoad, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DatLoad, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyphy.new_DatLoad(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_DatLoad
    __del__ = lambda self: None

    def get_columns_count(self):
        return _pyphy.DatLoad_get_columns_count(self)

    def get_lines_count(self):
        return _pyphy.DatLoad_get_lines_count(self)

    def get(self, column, line):
        return _pyphy.DatLoad_get(self, column, line)

    def set(self, column, line, value):
        return _pyphy.DatLoad_set(self, column, line, value)

    def get_max(self):
        return _pyphy.DatLoad_get_max(self)

    def get_max_column(self, column):
        return _pyphy.DatLoad_get_max_column(self, column)

    def get_min(self):
        return _pyphy.DatLoad_get_min(self)

    def get_min_column(self, column):
        return _pyphy.DatLoad_get_min_column(self, column)

    def normalise_per_column(self, min=0.0, max=1.0):
        return _pyphy.DatLoad_normalise_per_column(self, min, max)

    def normalise(self, min=0.0, max=1.0):
        return _pyphy.DatLoad_normalise(self, min, max)

    def normalise_column_kq(self, column, k, q):
        return _pyphy.DatLoad_normalise_column_kq(self, column, k, q)

    def _print(self, verbose=False):
        return _pyphy.DatLoad__print(self, verbose)

    def save(self, file_name):
        return _pyphy.DatLoad_save(self, file_name)

    def process_modulo(self, modulo):
        return _pyphy.DatLoad_process_modulo(self, modulo)

    def load(self, file_name):
        return _pyphy.DatLoad_load(self, file_name)

    def find_extreme(self):
        return _pyphy.DatLoad_find_extreme(self)
DatLoad_swigregister = _pyphy.DatLoad_swigregister
DatLoad_swigregister(DatLoad)

class DatsLoad(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DatsLoad, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DatsLoad, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyphy.new_DatsLoad(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_DatsLoad
    __del__ = lambda self: None

    def _print(self):
        return _pyphy.DatsLoad__print(self)

    def save(self, file_name_prefix):
        return _pyphy.DatsLoad_save(self, file_name_prefix)

    def get(self, dat_idx, column_idx, line_idx):
        return _pyphy.DatsLoad_get(self, dat_idx, column_idx, line_idx)

    def set(self, dat_idx, column_idx, line_idx, value):
        return _pyphy.DatsLoad_set(self, dat_idx, column_idx, line_idx, value)

    def get_dat_count(self):
        return _pyphy.DatsLoad_get_dat_count(self)

    def get_columns_count(self):
        return _pyphy.DatsLoad_get_columns_count(self)

    def get_lines_count(self):
        return _pyphy.DatsLoad_get_lines_count(self)

    def get_max(self):
        return _pyphy.DatsLoad_get_max(self)

    def get_max_column(self, column):
        return _pyphy.DatsLoad_get_max_column(self, column)

    def get_min(self):
        return _pyphy.DatsLoad_get_min(self)

    def get_min_column(self, column):
        return _pyphy.DatsLoad_get_min_column(self, column)

    def normalise_column(self, min=0.0, max=1.0, find_own_extreme=True):
        return _pyphy.DatsLoad_normalise_column(self, min, max, find_own_extreme)

    def get_extremes(self):
        return _pyphy.DatsLoad_get_extremes(self)

    def set_extremes(self, extremes):
        return _pyphy.DatsLoad_set_extremes(self, extremes)

    def find_extreme(self):
        return _pyphy.DatsLoad_find_extreme(self)

    def get_values_modulo(self):
        return _pyphy.DatsLoad_get_values_modulo(self)
DatsLoad_swigregister = _pyphy.DatsLoad_swigregister
DatsLoad_swigregister(DatsLoad)

class sMotionTensorExtreme(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, sMotionTensorExtreme, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, sMotionTensorExtreme, name)
    __repr__ = _swig_repr
    __swig_setmethods__["min"] = _pyphy.sMotionTensorExtreme_min_set
    __swig_getmethods__["min"] = _pyphy.sMotionTensorExtreme_min_get
    if _newclass:
        min = _swig_property(_pyphy.sMotionTensorExtreme_min_get, _pyphy.sMotionTensorExtreme_min_set)
    __swig_setmethods__["max"] = _pyphy.sMotionTensorExtreme_max_set
    __swig_getmethods__["max"] = _pyphy.sMotionTensorExtreme_max_get
    if _newclass:
        max = _swig_property(_pyphy.sMotionTensorExtreme_max_get, _pyphy.sMotionTensorExtreme_max_set)

    def __init__(self):
        this = _pyphy.new_sMotionTensorExtreme()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_sMotionTensorExtreme
    __del__ = lambda self: None
sMotionTensorExtreme_swigregister = _pyphy.sMotionTensorExtreme_swigregister
sMotionTensorExtreme_swigregister(sMotionTensorExtreme)

class MotionTensor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MotionTensor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MotionTensor, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyphy.new_MotionTensor(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_MotionTensor
    __del__ = lambda self: None

    def init(self, width_, height_, depth_):
        return _pyphy.MotionTensor_init(self, width_, height_, depth_)

    def get(self, x, y, z):
        return _pyphy.MotionTensor_get(self, x, y, z)

    def set(self, x, y, z, value):
        return _pyphy.MotionTensor_set(self, x, y, z, value)

    def width(self):
        return _pyphy.MotionTensor_width(self)

    def height(self):
        return _pyphy.MotionTensor_height(self)

    def depth(self):
        return _pyphy.MotionTensor_depth(self)

    def set_extremes(self, extremes):
        return _pyphy.MotionTensor_set_extremes(self, extremes)

    def get_extremes(self):
        return _pyphy.MotionTensor_get_extremes(self)

    def _print(self, verbose=False):
        return _pyphy.MotionTensor__print(self, verbose)

    def clear(self):
        return _pyphy.MotionTensor_clear(self)

    def normalise(self):
        return _pyphy.MotionTensor_normalise(self)

    def add_noise(self, noise_level):
        return _pyphy.MotionTensor_add_noise(self, noise_level)

    def velocity_from_position(self):
        return _pyphy.MotionTensor_velocity_from_position(self)

    def save(self, file_name_prefix):
        return _pyphy.MotionTensor_save(self, file_name_prefix)

    def save_json(self, file_name):
        return _pyphy.MotionTensor_save_json(self, file_name)

    def load_json(self, file_name):
        return _pyphy.MotionTensor_load_json(self, file_name)

    def find_extremes(self):
        return _pyphy.MotionTensor_find_extremes(self)
MotionTensor_swigregister = _pyphy.MotionTensor_swigregister
MotionTensor_swigregister(MotionTensor)

class DatsToMotionTensor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DatsToMotionTensor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DatsToMotionTensor, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyphy.new_DatsToMotionTensor(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_DatsToMotionTensor
    __del__ = lambda self: None

    def load(self, *args):
        return _pyphy.DatsToMotionTensor_load(self, *args)

    def get_values_modulo(self):
        return _pyphy.DatsToMotionTensor_get_values_modulo(self)

    def tensor(self):
        return _pyphy.DatsToMotionTensor_tensor(self)
DatsToMotionTensor_swigregister = _pyphy.DatsToMotionTensor_swigregister
DatsToMotionTensor_swigregister(DatsToMotionTensor)

class sDatasetItem(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, sDatasetItem, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, sDatasetItem, name)
    __repr__ = _swig_repr
    __swig_setmethods__["input"] = _pyphy.sDatasetItem_input_set
    __swig_getmethods__["input"] = _pyphy.sDatasetItem_input_get
    if _newclass:
        input = _swig_property(_pyphy.sDatasetItem_input_get, _pyphy.sDatasetItem_input_set)
    __swig_setmethods__["output"] = _pyphy.sDatasetItem_output_set
    __swig_getmethods__["output"] = _pyphy.sDatasetItem_output_get
    if _newclass:
        output = _swig_property(_pyphy.sDatasetItem_output_get, _pyphy.sDatasetItem_output_set)

    def __init__(self):
        this = _pyphy.new_sDatasetItem()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_sDatasetItem
    __del__ = lambda self: None
sDatasetItem_swigregister = _pyphy.sDatasetItem_swigregister
sDatasetItem_swigregister(sDatasetItem)

class TensorInterface(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TensorInterface, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TensorInterface, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyphy.new_TensorInterface(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_TensorInterface
    __del__ = lambda self: None

    def get(self):
        return _pyphy.TensorInterface_get(self)

    def input_width(self):
        return _pyphy.TensorInterface_input_width(self)

    def input_height(self):
        return _pyphy.TensorInterface_input_height(self)

    def input_depth(self):
        return _pyphy.TensorInterface_input_depth(self)

    def output_width(self):
        return _pyphy.TensorInterface_output_width(self)

    def output_height(self):
        return _pyphy.TensorInterface_output_height(self)

    def output_depth(self):
        return _pyphy.TensorInterface_output_depth(self)

    def input_size(self):
        return _pyphy.TensorInterface_input_size(self)

    def output_size(self):
        return _pyphy.TensorInterface_output_size(self)

    def asString(self):
        return _pyphy.TensorInterface_asString(self)

    def _print(self):
        return _pyphy.TensorInterface__print(self)

    def get_max_y_offset(self):
        return _pyphy.TensorInterface_get_max_y_offset(self)

    def get_max_z_offset(self):
        return _pyphy.TensorInterface_get_max_z_offset(self)

    def create(self, *args):
        return _pyphy.TensorInterface_create(self, *args)
TensorInterface_swigregister = _pyphy.TensorInterface_swigregister
TensorInterface_swigregister(TensorInterface)

class TensorNoSpatial(TensorInterface):
    __swig_setmethods__ = {}
    for _s in [TensorInterface]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TensorNoSpatial, name, value)
    __swig_getmethods__ = {}
    for _s in [TensorInterface]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, TensorNoSpatial, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyphy.new_TensorNoSpatial(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_TensorNoSpatial
    __del__ = lambda self: None

    def create(self, *args):
        return _pyphy.TensorNoSpatial_create(self, *args)
TensorNoSpatial_swigregister = _pyphy.TensorNoSpatial_swigregister
TensorNoSpatial_swigregister(TensorNoSpatial)

class TensorSpatial(TensorInterface):
    __swig_setmethods__ = {}
    for _s in [TensorInterface]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TensorSpatial, name, value)
    __swig_getmethods__ = {}
    for _s in [TensorInterface]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, TensorSpatial, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyphy.new_TensorSpatial(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_TensorSpatial
    __del__ = lambda self: None

    def create(self, *args):
        return _pyphy.TensorSpatial_create(self, *args)
TensorSpatial_swigregister = _pyphy.TensorSpatial_swigregister
TensorSpatial_swigregister(TensorSpatial)

class DatasetInterface(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DatasetInterface, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DatasetInterface, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyphy.new_DatasetInterface(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_DatasetInterface
    __del__ = lambda self: None

    def get_input_shape(self):
        return _pyphy.DatasetInterface_get_input_shape(self)

    def get_output_shape(self):
        return _pyphy.DatasetInterface_get_output_shape(self)

    def get_training_count(self):
        return _pyphy.DatasetInterface_get_training_count(self)

    def get_testing_count(self):
        return _pyphy.DatasetInterface_get_testing_count(self)

    def get_classes_count(self):
        return _pyphy.DatasetInterface_get_classes_count(self)

    def set_training_idx(self, idx):
        return _pyphy.DatasetInterface_set_training_idx(self, idx)

    def set_random_training_idx(self):
        return _pyphy.DatasetInterface_set_random_training_idx(self)

    def get_training_input(self):
        return _pyphy.DatasetInterface_get_training_input(self)

    def get_training_output(self):
        return _pyphy.DatasetInterface_get_training_output(self)

    def get_training_input_all(self):
        return _pyphy.DatasetInterface_get_training_input_all(self)

    def get_training_output_all(self):
        return _pyphy.DatasetInterface_get_training_output_all(self)

    def get_testing_input(self, idx):
        return _pyphy.DatasetInterface_get_testing_input(self, idx)

    def get_testing_output(self, idx):
        return _pyphy.DatasetInterface_get_testing_output(self, idx)

    def get_testing_input_all(self):
        return _pyphy.DatasetInterface_get_testing_input_all(self)

    def get_testing_output_all(self):
        return _pyphy.DatasetInterface_get_testing_output_all(self)

    def set_input_shape(self, input_shape):
        return _pyphy.DatasetInterface_set_input_shape(self, input_shape)

    def set_output_shape(self, output_shape):
        return _pyphy.DatasetInterface_set_output_shape(self, output_shape)

    def add_training(self, input, output):
        return _pyphy.DatasetInterface_add_training(self, input, output)

    def add_testing(self, input, output):
        return _pyphy.DatasetInterface_add_testing(self, input, output)

    def _print(self):
        return _pyphy.DatasetInterface__print(self)

    def clear(self):
        return _pyphy.DatasetInterface_clear(self)

    def normalise_input(self):
        return _pyphy.DatasetInterface_normalise_input(self)

    def normalise_output(self):
        return _pyphy.DatasetInterface_normalise_output(self)
DatasetInterface_swigregister = _pyphy.DatasetInterface_swigregister
DatasetInterface_swigregister(DatasetInterface)

class DatasetVelocitySimple(DatasetInterface):
    __swig_setmethods__ = {}
    for _s in [DatasetInterface]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DatasetVelocitySimple, name, value)
    __swig_getmethods__ = {}
    for _s in [DatasetInterface]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DatasetVelocitySimple, name)
    __repr__ = _swig_repr

    def __init__(self, training_dats_json_file_name, testing_dats_json_file_name, motion_tensor_file_name, training_count, testing_count):
        this = _pyphy.new_DatasetVelocitySimple(training_dats_json_file_name, testing_dats_json_file_name, motion_tensor_file_name, training_count, testing_count)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_DatasetVelocitySimple
    __del__ = lambda self: None
DatasetVelocitySimple_swigregister = _pyphy.DatasetVelocitySimple_swigregister
DatasetVelocitySimple_swigregister(DatasetVelocitySimple)

class DatasetTrajectory(DatasetInterface):
    __swig_setmethods__ = {}
    for _s in [DatasetInterface]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DatasetTrajectory, name, value)
    __swig_getmethods__ = {}
    for _s in [DatasetInterface]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DatasetTrajectory, name)
    __repr__ = _swig_repr

    def __init__(self, training_tensor_interface, testing_tensor_interface, training_count=0, testing_count=0):
        this = _pyphy.new_DatasetTrajectory(training_tensor_interface, testing_tensor_interface, training_count, testing_count)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_DatasetTrajectory
    __del__ = lambda self: None
DatasetTrajectory_swigregister = _pyphy.DatasetTrajectory_swigregister
DatasetTrajectory_swigregister(DatasetTrajectory)

class DatasetTrajectoryRuntime(DatasetInterface):
    __swig_setmethods__ = {}
    for _s in [DatasetInterface]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DatasetTrajectoryRuntime, name, value)
    __swig_getmethods__ = {}
    for _s in [DatasetInterface]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DatasetTrajectoryRuntime, name)
    __repr__ = _swig_repr

    def __init__(self, training_tensor_interface, testing_tensor_interface, testing_count):
        this = _pyphy.new_DatasetTrajectoryRuntime(training_tensor_interface, testing_tensor_interface, testing_count)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_DatasetTrajectoryRuntime
    __del__ = lambda self: None

    def get_training_count(self):
        return _pyphy.DatasetTrajectoryRuntime_get_training_count(self)

    def get_testing_count(self):
        return _pyphy.DatasetTrajectoryRuntime_get_testing_count(self)

    def set_random_training_idx(self):
        return _pyphy.DatasetTrajectoryRuntime_set_random_training_idx(self)

    def get_training_input(self):
        return _pyphy.DatasetTrajectoryRuntime_get_training_input(self)

    def get_training_output(self):
        return _pyphy.DatasetTrajectoryRuntime_get_training_output(self)

    def get_testing_input(self, idx):
        return _pyphy.DatasetTrajectoryRuntime_get_testing_input(self, idx)

    def get_testing_output(self, idx):
        return _pyphy.DatasetTrajectoryRuntime_get_testing_output(self, idx)
DatasetTrajectoryRuntime_swigregister = _pyphy.DatasetTrajectoryRuntime_swigregister
DatasetTrajectoryRuntime_swigregister(DatasetTrajectoryRuntime)

class MotionTensorVisualisation(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MotionTensorVisualisation, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MotionTensorVisualisation, name)
    __repr__ = _swig_repr

    def __init__(self, points_max_count=0):
        this = _pyphy.new_MotionTensorVisualisation(points_max_count)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_MotionTensorVisualisation
    __del__ = lambda self: None

    def start(self):
        return _pyphy.MotionTensorVisualisation_start(self)

    def render(self, motion_tensor, r, g, b, view_mode=0, min=0, max=0):
        return _pyphy.MotionTensorVisualisation_render(self, motion_tensor, r, g, b, view_mode, min, max)

    def finish(self):
        return _pyphy.MotionTensorVisualisation_finish(self)

    def new_loop(self):
        return _pyphy.MotionTensorVisualisation_new_loop(self)
MotionTensorVisualisation_swigregister = _pyphy.MotionTensorVisualisation_swigregister
MotionTensorVisualisation_swigregister(MotionTensorVisualisation)

class Log(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Log, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Log, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyphy.new_Log(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_Log
    __del__ = lambda self: None

    def set_output_file_name(self, file_name):
        return _pyphy.Log_set_output_file_name(self, file_name)

    def put_string(self, str):
        return _pyphy.Log_put_string(self, str)

    def __lshift__(self, *args):
        return _pyphy.Log___lshift__(self, *args)
Log_swigregister = _pyphy.Log_swigregister
Log_swigregister(Log)

class JsonConfig(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, JsonConfig, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, JsonConfig, name)
    __repr__ = _swig_repr
    __swig_setmethods__["result"] = _pyphy.JsonConfig_result_set
    __swig_getmethods__["result"] = _pyphy.JsonConfig_result_get
    if _newclass:
        result = _swig_property(_pyphy.JsonConfig_result_get, _pyphy.JsonConfig_result_set)

    def __init__(self, *args):
        this = _pyphy.new_JsonConfig(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_JsonConfig
    __del__ = lambda self: None

    def load(self, json_file_name):
        return _pyphy.JsonConfig_load(self, json_file_name)

    def save(self, file_name):
        return _pyphy.JsonConfig_save(self, file_name)

    def get(self):
        return _pyphy.JsonConfig_get(self)
JsonConfig_swigregister = _pyphy.JsonConfig_swigregister
JsonConfig_swigregister(JsonConfig)

class RegressionExperiment(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RegressionExperiment, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RegressionExperiment, name)
    __repr__ = _swig_repr

    def __init__(self, dataset, experiment_dir, network_config_file):
        this = _pyphy.new_RegressionExperiment(dataset, experiment_dir, network_config_file)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_RegressionExperiment
    __del__ = lambda self: None

    def run(self):
        return _pyphy.RegressionExperiment_run(self)
RegressionExperiment_swigregister = _pyphy.RegressionExperiment_swigregister
RegressionExperiment_swigregister(RegressionExperiment)

class TrajectoryPrediction(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TrajectoryPrediction, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TrajectoryPrediction, name)
    __repr__ = _swig_repr

    def __init__(self, initial_conditions):
        this = _pyphy.new_TrajectoryPrediction(initial_conditions)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_TrajectoryPrediction
    __del__ = lambda self: None

    def process(self, *args):
        return _pyphy.TrajectoryPrediction_process(self, *args)

    def get_result(self):
        return _pyphy.TrajectoryPrediction_get_result(self)
TrajectoryPrediction_swigregister = _pyphy.TrajectoryPrediction_swigregister
TrajectoryPrediction_swigregister(TrajectoryPrediction)

class VelocityPrediction(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VelocityPrediction, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VelocityPrediction, name)
    __repr__ = _swig_repr

    def __init__(self, target_trajectory):
        this = _pyphy.new_VelocityPrediction(target_trajectory)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_VelocityPrediction
    __del__ = lambda self: None

    def process(self, network_file_name, tensor_interface, prediction_offset):
        return _pyphy.VelocityPrediction_process(self, network_file_name, tensor_interface, prediction_offset)

    def get_result(self):
        return _pyphy.VelocityPrediction_get_result(self)
VelocityPrediction_swigregister = _pyphy.VelocityPrediction_swigregister
VelocityPrediction_swigregister(VelocityPrediction)

class LoadTextures(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LoadTextures, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LoadTextures, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyphy.new_LoadTextures(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_LoadTextures
    __del__ = lambda self: None

    def load(self, file_name):
        return _pyphy.LoadTextures_load(self, file_name)

    def get_textures_count(self):
        return _pyphy.LoadTextures_get_textures_count(self)

    def get(self, id):
        return _pyphy.LoadTextures_get(self, id)

    def get_idx(self, idx):
        return _pyphy.LoadTextures_get_idx(self, idx)
LoadTextures_swigregister = _pyphy.LoadTextures_swigregister
LoadTextures_swigregister(LoadTextures)

class GLVisualisation(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GLVisualisation, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GLVisualisation, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _pyphy.new_GLVisualisation()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pyphy.delete_GLVisualisation
    __del__ = lambda self: None

    def time(self):
        return _pyphy.GLVisualisation_time(self)

    def init(self, *args):
        return _pyphy.GLVisualisation_init(self, *args)

    def width(self):
        return _pyphy.GLVisualisation_width(self)

    def height(self):
        return _pyphy.GLVisualisation_height(self)

    def start(self):
        return _pyphy.GLVisualisation_start(self)

    def finish(self):
        return _pyphy.GLVisualisation_finish(self)

    def push(self):
        return _pyphy.GLVisualisation_push(self)

    def pop(self):
        return _pyphy.GLVisualisation_pop(self)

    def translate(self, x, y, z):
        return _pyphy.GLVisualisation_translate(self, x, y, z)

    def rotate(self, angle_x, angle_y, angle_z):
        return _pyphy.GLVisualisation_rotate(self, angle_x, angle_y, angle_z)

    def set_color(self, r, g, b):
        return _pyphy.GLVisualisation_set_color(self, r, g, b)

    def paint_point(self):
        return _pyphy.GLVisualisation_paint_point(self)

    def paint_square(self, size):
        return _pyphy.GLVisualisation_paint_square(self, size)

    def paint_rectangle(self, width, height):
        return _pyphy.GLVisualisation_paint_rectangle(self, width, height)

    def paint_textured_rectangle(self, width, height, texture_id):
        return _pyphy.GLVisualisation_paint_textured_rectangle(self, width, height, texture_id)

    def paint_line(self, x0, y0, z0, x1, y1, z1):
        return _pyphy.GLVisualisation_paint_line(self, x0, y0, z0, x1, y1, z1)

    def paint_quad(self, x0, y0, z0, r0, g0, b0, x1, y1, z1, r1, g1, b1, x2, y2, z2, r2, g2, b2, x3, y3, z3, r3, g3, b3):
        return _pyphy.GLVisualisation_paint_quad(self, x0, y0, z0, r0, g0, b0, x1, y1, z1, r1, g1, b1, x2, y2, z2, r2, g2, b2, x3, y3, z3, r3, g3, b3)

    def paint_cube(self, size):
        return _pyphy.GLVisualisation_paint_cube(self, size)

    def paint_cuboid(self, width, height, depth):
        return _pyphy.GLVisualisation_paint_cuboid(self, width, height, depth)

    def paint_circle(self, size, steps=12):
        return _pyphy.GLVisualisation_paint_circle(self, size, steps)

    def paint_sphere(self, size, steps=12):
        return _pyphy.GLVisualisation_paint_sphere(self, size, steps)

    def _print(self, x, y, z, string, small_font=False):
        return _pyphy.GLVisualisation__print(self, x, y, z, string, small_font)

    def get_key(self):
        return _pyphy.GLVisualisation_get_key(self)

    def get_texture(self, id):
        return _pyphy.GLVisualisation_get_texture(self, id)
GLVisualisation_swigregister = _pyphy.GLVisualisation_swigregister
GLVisualisation_swigregister(GLVisualisation)

# This file is compatible with both classic and new-style classes.


